SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS agent_teams (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  owner_user_id BIGINT UNSIGNED NULL,
  owner_key VARCHAR(128) NOT NULL,
  team_key VARCHAR(64) NOT NULL,
  team_version INT UNSIGNED NOT NULL,
  scope VARCHAR(24) NOT NULL DEFAULT 'tenant_shared',
  display_name VARCHAR(128) NOT NULL,
  description TEXT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  schema_version INT UNSIGNED NOT NULL DEFAULT 1,
  policy_json JSON NOT NULL,
  requested_hash CHAR(64) NOT NULL,
  effective_hash CHAR(64) NOT NULL,
  validation_json JSON NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  updated_by_user_id BIGINT UNSIGNED NOT NULL,
  published_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_agent_teams_tenant_id (tenant_id, id),
  UNIQUE KEY uk_agent_teams_version (tenant_id, team_key, team_version),
  KEY idx_agent_teams_latest (tenant_id, team_key, status, updated_at),
  CONSTRAINT chk_agent_teams_scope CHECK (scope IN ('tenant_shared', 'user_private')),
  CONSTRAINT chk_agent_teams_status CHECK (status IN ('draft', 'validating', 'published', 'archived')),
  CONSTRAINT fk_agent_teams_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_agent_teams_owner_tenant FOREIGN KEY (tenant_id, owner_user_id) REFERENCES tenant_users(tenant_id, id),
  CONSTRAINT fk_agent_teams_created_by_tenant FOREIGN KEY (tenant_id, created_by_user_id) REFERENCES tenant_users(tenant_id, id),
  CONSTRAINT fk_agent_teams_updated_by_tenant FOREIGN KEY (tenant_id, updated_by_user_id) REFERENCES tenant_users(tenant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_team_members (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  team_id BIGINT UNSIGNED NOT NULL,
  member_key VARCHAR(64) NOT NULL,
  profile_id BIGINT UNSIGNED NOT NULL,
  role VARCHAR(32) NOT NULL,
  account_id BIGINT UNSIGNED NULL,
  tool_policy_json JSON NULL,
  workspace_policy_json JSON NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_agent_team_members_tenant_id (tenant_id, id),
  UNIQUE KEY uk_agent_team_members_key (team_id, member_key),
  KEY idx_agent_team_members_profile (tenant_id, profile_id),
  CONSTRAINT chk_agent_team_members_status CHECK (status IN ('active', 'archived')),
  CONSTRAINT fk_agent_team_members_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_agent_team_members_team_tenant FOREIGN KEY (tenant_id, team_id) REFERENCES agent_teams(tenant_id, id),
  CONSTRAINT fk_agent_team_members_profile_tenant FOREIGN KEY (tenant_id, profile_id) REFERENCES agent_profiles(tenant_id, id),
  CONSTRAINT fk_agent_team_members_account_tenant FOREIGN KEY (tenant_id, account_id) REFERENCES channel_accounts(tenant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_team_bindings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  team_id BIGINT UNSIGNED NOT NULL,
  provider VARCHAR(32) NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  external_chat_id VARCHAR(255) NOT NULL,
  external_thread_id VARCHAR(255) NOT NULL DEFAULT '',
  trigger_policy VARCHAR(24) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_agent_team_bindings_tenant_id (tenant_id, id),
  UNIQUE KEY uk_agent_team_bindings_external (team_id, provider, account_id, external_chat_id, external_thread_id),
  KEY idx_agent_team_bindings_route (tenant_id, provider, account_id, external_chat_id, external_thread_id, status),
  CONSTRAINT chk_agent_team_bindings_trigger CHECK (trigger_policy IN ('mention', 'command', 'internal_only')),
  CONSTRAINT chk_agent_team_bindings_status CHECK (status IN ('active', 'archived')),
  CONSTRAINT fk_agent_team_bindings_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_agent_team_bindings_team_tenant FOREIGN KEY (tenant_id, team_id) REFERENCES agent_teams(tenant_id, id),
  CONSTRAINT fk_agent_team_bindings_account_tenant FOREIGN KEY (tenant_id, account_id) REFERENCES channel_accounts(tenant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_team_runs (
  id CHAR(36) NOT NULL,
  tenant_id BIGINT UNSIGNED NOT NULL,
  team_id BIGINT UNSIGNED NOT NULL,
  inbox_event_id BIGINT UNSIGNED NOT NULL,
  source_account_id BIGINT UNSIGNED NOT NULL,
  conversation_id BIGINT UNSIGNED NULL,
  coordinator_member_key VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'queued',
  team_effective_hash CHAR(64) NOT NULL,
  member_count INT UNSIGNED NOT NULL DEFAULT 0,
  max_rounds INT UNSIGNED NOT NULL DEFAULT 0,
  max_parallel_members INT UNSIGNED NOT NULL DEFAULT 0,
  max_total_tokens INT UNSIGNED NOT NULL DEFAULT 0,
  used_tokens INT UNSIGNED NOT NULL DEFAULT 0,
  used_turns INT UNSIGNED NOT NULL DEFAULT 0,
  heartbeat_at DATETIME(3) NULL,
  cancel_requested_at DATETIME(3) NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  result_json JSON NULL,
  error_code VARCHAR(128) NULL,
  error_message VARCHAR(1024) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_agent_team_runs_tenant_id (tenant_id, id),
  UNIQUE KEY uk_agent_team_runs_inbox (tenant_id, inbox_event_id),
  KEY idx_agent_team_runs_team_status (tenant_id, team_id, status, created_at),
  KEY idx_agent_team_runs_heartbeat (status, heartbeat_at),
  CONSTRAINT chk_agent_team_runs_status CHECK (status IN ('queued', 'running', 'waiting_input', 'completed', 'partial', 'cancelled', 'failed', 'timed_out')),
  CONSTRAINT fk_agent_team_runs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_agent_team_runs_team_tenant FOREIGN KEY (tenant_id, team_id) REFERENCES agent_teams(tenant_id, id),
  CONSTRAINT fk_agent_team_runs_inbox_tenant FOREIGN KEY (tenant_id, inbox_event_id) REFERENCES channel_inbox_events(tenant_id, id),
  CONSTRAINT fk_agent_team_runs_account_tenant FOREIGN KEY (tenant_id, source_account_id) REFERENCES channel_accounts(tenant_id, id),
  CONSTRAINT fk_agent_team_runs_conversation_tenant FOREIGN KEY (tenant_id, conversation_id) REFERENCES channel_conversations(tenant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_team_mailbox (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  team_run_id CHAR(36) NOT NULL,
  from_member_key VARCHAR(64) NOT NULL,
  to_member_key VARCHAR(64) NOT NULL,
  message_kind VARCHAR(32) NOT NULL,
  sequence_no BIGINT UNSIGNED NOT NULL,
  idempotency_key VARCHAR(255) NOT NULL,
  payload_ref VARCHAR(1024) NULL,
  payload_ciphertext MEDIUMBLOB NULL,
  evidence_ref VARCHAR(1024) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  lease_owner VARCHAR(255) NULL,
  lease_until DATETIME(3) NULL,
  consumed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_agent_team_mailbox_tenant_id (tenant_id, id),
  UNIQUE KEY uk_agent_team_mailbox_idempotency (tenant_id, team_run_id, idempotency_key),
  UNIQUE KEY uk_agent_team_mailbox_sequence (tenant_id, team_run_id, sequence_no),
  KEY idx_agent_team_mailbox_claim (tenant_id, team_run_id, status, lease_until, sequence_no),
  CONSTRAINT chk_agent_team_mailbox_status CHECK (status IN ('pending', 'leased', 'consumed', 'failed', 'dead')),
  CONSTRAINT fk_agent_team_mailbox_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_agent_team_mailbox_run_tenant FOREIGN KEY (tenant_id, team_run_id) REFERENCES agent_team_runs(tenant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
