SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS tenant_quota_configs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  quota_enabled TINYINT(1) NOT NULL DEFAULT 0,
  qps_limit BIGINT UNSIGNED NULL,
  daily_token_limit BIGINT UNSIGNED NULL,
  daily_message_limit BIGINT UNSIGNED NULL,
  max_concurrent_requests BIGINT UNSIGNED NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
  reserve_output_tokens BIGINT UNSIGNED NOT NULL DEFAULT 4096,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  updated_by_user_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_tenant_quota_config_tenant (tenant_id),
  KEY idx_tenant_quota_config_enabled (quota_enabled, status),
  CONSTRAINT fk_tenant_quota_config_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_tenant_quota_config_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES tenant_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tenant_usage_ledger (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  request_id VARCHAR(128) NOT NULL,
  tenant_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  session_id BIGINT UNSIGNED NULL,
  trace_id VARCHAR(128) NULL,
  source VARCHAR(32) NOT NULL,
  route VARCHAR(128) NULL,
  model VARCHAR(128) NULL,
  status VARCHAR(32) NOT NULL,
  estimated TINYINT(1) NOT NULL DEFAULT 0,
  reserved_input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  reserved_output_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  output_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cache_read_input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cache_creation_input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  error_code VARCHAR(128) NULL,
  error_message VARCHAR(1024) NULL,
  started_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  finished_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_usage_ledger_request (request_id),
  KEY idx_usage_ledger_tenant_day (tenant_id, started_at, id),
  KEY idx_usage_ledger_user_day (tenant_id, user_id, started_at),
  KEY idx_usage_ledger_session (tenant_id, session_id),
  KEY idx_usage_ledger_trace (tenant_id, trace_id),
  KEY idx_usage_ledger_source_day (tenant_id, source, started_at),
  KEY idx_usage_ledger_model_day (tenant_id, model, started_at),
  KEY idx_usage_ledger_status_day (tenant_id, status, started_at),
  CONSTRAINT fk_usage_ledger_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_usage_ledger_user FOREIGN KEY (user_id) REFERENCES tenant_users(id),
  CONSTRAINT fk_usage_ledger_session FOREIGN KEY (session_id) REFERENCES tenant_sessions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tenant_usage_daily (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  usage_date DATE NOT NULL,
  source VARCHAR(32) NOT NULL DEFAULT '*',
  model VARCHAR(128) NOT NULL DEFAULT '*',
  request_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  message_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  output_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cache_read_input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cache_creation_input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  rejected_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_usage_daily_dim (tenant_id, usage_date, source, model),
  KEY idx_usage_daily_date (usage_date, tenant_id),
  CONSTRAINT fk_usage_daily_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tenant_quota_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  request_id VARCHAR(128) NULL,
  event_type VARCHAR(128) NOT NULL,
  limit_type VARCHAR(64) NULL,
  limit_value BIGINT UNSIGNED NULL,
  current_value BIGINT UNSIGNED NULL,
  source VARCHAR(32) NULL,
  route VARCHAR(128) NULL,
  model VARCHAR(128) NULL,
  trace_id VARCHAR(128) NULL,
  metadata_json JSON NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_quota_events_tenant_recent (tenant_id, created_at, id),
  KEY idx_quota_events_type_recent (tenant_id, event_type, created_at),
  KEY idx_quota_events_trace (tenant_id, trace_id),
  CONSTRAINT fk_quota_events_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_quota_events_user FOREIGN KEY (user_id) REFERENCES tenant_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
