SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS channel_accounts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  provider VARCHAR(32) NOT NULL,
  account_key VARCHAR(128) NOT NULL,
  app_id VARCHAR(255) NOT NULL,
  credential_ref VARCHAR(512) NOT NULL,
  mode VARCHAR(16) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  policy_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'disabled',
  last_connected_at DATETIME(3) NULL,
  last_error_code VARCHAR(128) NULL,
  last_error_message VARCHAR(1024) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  archived_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_channel_accounts_tenant_provider_key (tenant_id, provider, account_key),
  KEY idx_channel_accounts_tenant_enabled_provider (tenant_id, enabled, provider),
  CONSTRAINT fk_channel_accounts_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS channel_identities (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  external_user_id VARCHAR(255) NOT NULL,
  external_union_id VARCHAR(255) NULL,
  user_id BIGINT UNSIGNED NULL,
  display_name VARCHAR(255) NULL,
  metadata_json JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  archived_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_channel_identities_account_external_user (account_id, external_user_id),
  KEY idx_channel_identities_tenant_user (tenant_id, user_id),
  CONSTRAINT fk_channel_identities_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_channel_identities_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id),
  CONSTRAINT fk_channel_identities_user FOREIGN KEY (user_id) REFERENCES tenant_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS channel_conversations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  external_chat_id VARCHAR(255) NOT NULL,
  external_thread_id VARCHAR(255) NOT NULL DEFAULT '',
  thread_id_source VARCHAR(32) NOT NULL DEFAULT 'none',
  scope_key VARCHAR(768) NOT NULL,
  scope_hash BINARY(32) NOT NULL,
  external_user_id VARCHAR(255) NULL,
  chat_type VARCHAR(16) NOT NULL,
  session_id BIGINT UNSIGNED NULL,
  runtime_fingerprint VARCHAR(64) NOT NULL DEFAULT '',
  runtime_fingerprint_version INT NOT NULL DEFAULT 1,
  workspace_realpath VARCHAR(1024) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  last_inbound_at DATETIME(3) NULL,
  last_outbound_at DATETIME(3) NULL,
  metadata_json JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  archived_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_channel_conversations_account_scope (account_id, scope_hash),
  UNIQUE KEY uk_channel_conversations_account_chat_thread (account_id, external_chat_id, external_thread_id),
  KEY idx_channel_conversations_tenant_inbound (tenant_id, last_inbound_at),
  KEY idx_channel_conversations_session (session_id),
  KEY idx_channel_conversations_account_scope_status (account_id, scope_hash, status),
  CONSTRAINT fk_channel_conversations_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_channel_conversations_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id),
  CONSTRAINT fk_channel_conversations_session FOREIGN KEY (session_id) REFERENCES tenant_sessions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS channel_inbox_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  conversation_id BIGINT UNSIGNED NULL,
  provider_event_id VARCHAR(255) NOT NULL,
  provider_message_id VARCHAR(255) NULL,
  scope_hash BINARY(32) NULL,
  payload_sha256 BINARY(32) NULL,
  payload_ciphertext MEDIUMBLOB NULL,
  payload_key_version VARCHAR(64) NULL,
  payload_ref VARCHAR(1024) NULL,
  payload_purged_at DATETIME(3) NULL,
  authorized TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'received',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  available_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  lease_owner VARCHAR(255) NULL,
  lease_until DATETIME(3) NULL,
  acked_at DATETIME(3) NULL,
  received_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  processed_at DATETIME(3) NULL,
  error_code VARCHAR(128) NULL,
  error_message VARCHAR(1024) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_channel_inbox_events_account_event (account_id, provider_event_id),
  UNIQUE KEY uk_channel_inbox_events_account_message (account_id, provider_message_id),
  KEY idx_channel_inbox_events_claim (status, available_at, lease_until),
  KEY idx_channel_inbox_events_scope (account_id, scope_hash, status),
  CONSTRAINT fk_channel_inbox_events_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_channel_inbox_events_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id),
  CONSTRAINT fk_channel_inbox_events_conversation FOREIGN KEY (conversation_id) REFERENCES channel_conversations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS channel_runs (
  id CHAR(36) NOT NULL,
  tenant_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  conversation_id BIGINT UNSIGNED NOT NULL,
  scope_hash BINARY(32) NOT NULL,
  session_id BIGINT UNSIGNED NULL,
  runtime_turn_id VARCHAR(255) NULL,
  worker_id VARCHAR(255) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'queued',
  runtime_fingerprint VARCHAR(64) NOT NULL DEFAULT '',
  runtime_fingerprint_version INT NOT NULL DEFAULT 1,
  heartbeat_at DATETIME(3) NULL,
  cancel_requested_at DATETIME(3) NULL,
  last_event_seq BIGINT UNSIGNED NOT NULL DEFAULT 0,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  error_code VARCHAR(128) NULL,
  error_message VARCHAR(1024) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_channel_runs_scope_status (account_id, scope_hash, status),
  KEY idx_channel_runs_tenant_recent (tenant_id, created_at),
  KEY idx_channel_runs_heartbeat (status, heartbeat_at),
  CONSTRAINT fk_channel_runs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_channel_runs_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id),
  CONSTRAINT fk_channel_runs_conversation FOREIGN KEY (conversation_id) REFERENCES channel_conversations(id),
  CONSTRAINT fk_channel_runs_session FOREIGN KEY (session_id) REFERENCES tenant_sessions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS channel_messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  conversation_id BIGINT UNSIGNED NOT NULL,
  run_id CHAR(36) NULL,
  direction VARCHAR(16) NOT NULL,
  operation VARCHAR(16) NOT NULL,
  external_message_id VARCHAR(255) NOT NULL DEFAULT '',
  internal_message_id BIGINT UNSIGNED NULL,
  idempotency_key VARCHAR(255) NOT NULL,
  content_json JSON NOT NULL,
  render_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  last_render_sha256 BINARY(32) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  sent_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_channel_messages_conversation_direction_external (conversation_id, direction, external_message_id),
  KEY idx_channel_messages_conversation_created (conversation_id, created_at),
  KEY idx_channel_messages_status_created (status, created_at),
  CONSTRAINT fk_channel_messages_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_channel_messages_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id),
  CONSTRAINT fk_channel_messages_conversation FOREIGN KEY (conversation_id) REFERENCES channel_conversations(id),
  CONSTRAINT fk_channel_messages_run FOREIGN KEY (run_id) REFERENCES channel_runs(id),
  CONSTRAINT fk_channel_messages_internal FOREIGN KEY (internal_message_id) REFERENCES tenant_session_messages(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS channel_outbox (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  conversation_id BIGINT UNSIGNED NOT NULL,
  run_id CHAR(36) NULL,
  message_id BIGINT UNSIGNED NOT NULL,
  operation VARCHAR(16) NOT NULL,
  sequence_no INT UNSIGNED NOT NULL DEFAULT 0,
  chunk_count INT UNSIGNED NOT NULL DEFAULT 1,
  idempotency_key VARCHAR(255) NOT NULL,
  payload_json JSON NOT NULL,
  render_sha256 BINARY(32) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  next_attempt_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  retry_after_ms INT UNSIGNED NULL,
  lease_owner VARCHAR(255) NULL,
  lease_until DATETIME(3) NULL,
  last_error_code VARCHAR(128) NULL,
  last_error_message VARCHAR(1024) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  sent_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_channel_outbox_delivery (account_id, idempotency_key, sequence_no, operation),
  CHECK (status IN ('pending', 'sending', 'sent', 'retry', 'delivery_unknown', 'dead')),
  KEY idx_channel_outbox_status_next_attempt (status, next_attempt_at),
  KEY idx_channel_outbox_account_status (account_id, status),
  KEY idx_channel_outbox_conversation_created (conversation_id, created_at),
  CONSTRAINT fk_channel_outbox_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_channel_outbox_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id),
  CONSTRAINT fk_channel_outbox_conversation FOREIGN KEY (conversation_id) REFERENCES channel_conversations(id),
  CONSTRAINT fk_channel_outbox_run FOREIGN KEY (run_id) REFERENCES channel_runs(id),
  CONSTRAINT fk_channel_outbox_message FOREIGN KEY (message_id) REFERENCES channel_messages(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS channel_run_inputs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id CHAR(36) NOT NULL,
  inbox_event_id BIGINT UNSIGNED NOT NULL,
  sequence_no INT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_channel_run_inputs_inbox (inbox_event_id),
  UNIQUE KEY uk_channel_run_inputs_run_event (run_id, inbox_event_id),
  UNIQUE KEY uk_channel_run_inputs_run_sequence (run_id, sequence_no),
  CONSTRAINT fk_channel_run_inputs_run FOREIGN KEY (run_id) REFERENCES channel_runs(id),
  CONSTRAINT fk_channel_run_inputs_inbox FOREIGN KEY (inbox_event_id) REFERENCES channel_inbox_events(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS channel_callbacks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  conversation_id BIGINT UNSIGNED NOT NULL,
  run_id CHAR(36) NOT NULL,
  platform_message_id VARCHAR(255) NOT NULL,
  action_id VARCHAR(255) NOT NULL,
  nonce_hash BINARY(32) NOT NULL,
  runtime_fingerprint VARCHAR(64) NOT NULL,
  runtime_fingerprint_version INT NOT NULL,
  allowed_user_id BIGINT UNSIGNED NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  expires_at DATETIME(3) NOT NULL,
  consumed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_channel_callbacks_account_nonce (account_id, nonce_hash),
  KEY idx_channel_callbacks_expiry (status, expires_at),
  KEY idx_channel_callbacks_run (run_id, status),
  CONSTRAINT fk_channel_callbacks_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_channel_callbacks_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id),
  CONSTRAINT fk_channel_callbacks_conversation FOREIGN KEY (conversation_id) REFERENCES channel_conversations(id),
  CONSTRAINT fk_channel_callbacks_run FOREIGN KEY (run_id) REFERENCES channel_runs(id),
  CONSTRAINT fk_channel_callbacks_user FOREIGN KEY (allowed_user_id) REFERENCES tenant_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
