SET NAMES utf8mb4;

-- Remove only constraints owned by v12. Existing v11 constraints are restored
-- below, while pre-existing objects with other names remain untouched.
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_identities_account_tenant'), 'ALTER TABLE channel_identities DROP FOREIGN KEY fk_channel_v12_identities_account_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_identities_user_tenant'), 'ALTER TABLE channel_identities DROP FOREIGN KEY fk_channel_v12_identities_user_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_conversations_account_tenant'), 'ALTER TABLE channel_conversations DROP FOREIGN KEY fk_channel_v12_conversations_account_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_conversations_session_tenant'), 'ALTER TABLE channel_conversations DROP FOREIGN KEY fk_channel_v12_conversations_session_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_inbox_events_account_tenant'), 'ALTER TABLE channel_inbox_events DROP FOREIGN KEY fk_channel_v12_inbox_events_account_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_inbox_events_conversation_tenant'), 'ALTER TABLE channel_inbox_events DROP FOREIGN KEY fk_channel_v12_inbox_events_conversation_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_runs_account_tenant'), 'ALTER TABLE channel_runs DROP FOREIGN KEY fk_channel_v12_runs_account_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_runs_conversation_tenant'), 'ALTER TABLE channel_runs DROP FOREIGN KEY fk_channel_v12_runs_conversation_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_runs_session_tenant'), 'ALTER TABLE channel_runs DROP FOREIGN KEY fk_channel_v12_runs_session_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_messages_account_tenant'), 'ALTER TABLE channel_messages DROP FOREIGN KEY fk_channel_v12_messages_account_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_messages_conversation_tenant'), 'ALTER TABLE channel_messages DROP FOREIGN KEY fk_channel_v12_messages_conversation_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_messages_run_tenant'), 'ALTER TABLE channel_messages DROP FOREIGN KEY fk_channel_v12_messages_run_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_messages_internal_tenant'), 'ALTER TABLE channel_messages DROP FOREIGN KEY fk_channel_v12_messages_internal_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_outbox_account_tenant'), 'ALTER TABLE channel_outbox DROP FOREIGN KEY fk_channel_v12_outbox_account_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_outbox_conversation_tenant'), 'ALTER TABLE channel_outbox DROP FOREIGN KEY fk_channel_v12_outbox_conversation_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_outbox_run_tenant'), 'ALTER TABLE channel_outbox DROP FOREIGN KEY fk_channel_v12_outbox_run_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_outbox_message_tenant'), 'ALTER TABLE channel_outbox DROP FOREIGN KEY fk_channel_v12_outbox_message_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_run_inputs_run_tenant'), 'ALTER TABLE channel_run_inputs DROP FOREIGN KEY fk_channel_v12_run_inputs_run_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_run_inputs_inbox_tenant'), 'ALTER TABLE channel_run_inputs DROP FOREIGN KEY fk_channel_v12_run_inputs_inbox_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_callbacks_account_tenant'), 'ALTER TABLE channel_callbacks DROP FOREIGN KEY fk_channel_v12_callbacks_account_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_callbacks_conversation_tenant'), 'ALTER TABLE channel_callbacks DROP FOREIGN KEY fk_channel_v12_callbacks_conversation_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_callbacks_run_tenant'), 'ALTER TABLE channel_callbacks DROP FOREIGN KEY fk_channel_v12_callbacks_run_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;
SET @channel_v12_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND constraint_name = 'fk_channel_v12_callbacks_user_tenant'), 'ALTER TABLE channel_callbacks DROP FOREIGN KEY fk_channel_v12_callbacks_user_tenant', 'SELECT 1');
PREPARE channel_v12_drop_stmt FROM @channel_v12_drop_sql; EXECUTE channel_v12_drop_stmt; DEALLOCATE PREPARE channel_v12_drop_stmt;

SET @channel_v12_check_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_schema = DATABASE() AND table_name = 'channel_inbox_events' AND constraint_name = 'chk_channel_v12_inbox_payload_lifecycle'), 'ALTER TABLE channel_inbox_events DROP CHECK chk_channel_v12_inbox_payload_lifecycle', 'SELECT 1');
PREPARE channel_v12_check_drop_stmt FROM @channel_v12_check_drop_sql; EXECUTE channel_v12_check_drop_stmt; DEALLOCATE PREPARE channel_v12_check_drop_stmt;

SET @channel_v12_restore_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND table_name = 'channel_identities' AND constraint_name = 'fk_channel_identities_account'), 'SELECT 1', 'ALTER TABLE channel_identities ADD CONSTRAINT fk_channel_identities_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id), ADD CONSTRAINT fk_channel_identities_user FOREIGN KEY (user_id) REFERENCES tenant_users(id)');
PREPARE channel_v12_restore_stmt FROM @channel_v12_restore_sql; EXECUTE channel_v12_restore_stmt; DEALLOCATE PREPARE channel_v12_restore_stmt;
SET @channel_v12_restore_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND table_name = 'channel_conversations' AND constraint_name = 'fk_channel_conversations_account'), 'SELECT 1', 'ALTER TABLE channel_conversations ADD CONSTRAINT fk_channel_conversations_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id), ADD CONSTRAINT fk_channel_conversations_session FOREIGN KEY (session_id) REFERENCES tenant_sessions(id)');
PREPARE channel_v12_restore_stmt FROM @channel_v12_restore_sql; EXECUTE channel_v12_restore_stmt; DEALLOCATE PREPARE channel_v12_restore_stmt;
SET @channel_v12_restore_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND table_name = 'channel_inbox_events' AND constraint_name = 'fk_channel_inbox_events_account'), 'SELECT 1', 'ALTER TABLE channel_inbox_events ADD CONSTRAINT fk_channel_inbox_events_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id), ADD CONSTRAINT fk_channel_inbox_events_conversation FOREIGN KEY (conversation_id) REFERENCES channel_conversations(id)');
PREPARE channel_v12_restore_stmt FROM @channel_v12_restore_sql; EXECUTE channel_v12_restore_stmt; DEALLOCATE PREPARE channel_v12_restore_stmt;
SET @channel_v12_restore_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND table_name = 'channel_runs' AND constraint_name = 'fk_channel_runs_account'), 'SELECT 1', 'ALTER TABLE channel_runs ADD CONSTRAINT fk_channel_runs_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id), ADD CONSTRAINT fk_channel_runs_conversation FOREIGN KEY (conversation_id) REFERENCES channel_conversations(id), ADD CONSTRAINT fk_channel_runs_session FOREIGN KEY (session_id) REFERENCES tenant_sessions(id)');
PREPARE channel_v12_restore_stmt FROM @channel_v12_restore_sql; EXECUTE channel_v12_restore_stmt; DEALLOCATE PREPARE channel_v12_restore_stmt;
SET @channel_v12_restore_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND table_name = 'channel_messages' AND constraint_name = 'fk_channel_messages_account'), 'SELECT 1', 'ALTER TABLE channel_messages ADD CONSTRAINT fk_channel_messages_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id), ADD CONSTRAINT fk_channel_messages_conversation FOREIGN KEY (conversation_id) REFERENCES channel_conversations(id), ADD CONSTRAINT fk_channel_messages_run FOREIGN KEY (run_id) REFERENCES channel_runs(id), ADD CONSTRAINT fk_channel_messages_internal FOREIGN KEY (internal_message_id) REFERENCES tenant_session_messages(id)');
PREPARE channel_v12_restore_stmt FROM @channel_v12_restore_sql; EXECUTE channel_v12_restore_stmt; DEALLOCATE PREPARE channel_v12_restore_stmt;
SET @channel_v12_restore_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND table_name = 'channel_outbox' AND constraint_name = 'fk_channel_outbox_account'), 'SELECT 1', 'ALTER TABLE channel_outbox ADD CONSTRAINT fk_channel_outbox_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id), ADD CONSTRAINT fk_channel_outbox_conversation FOREIGN KEY (conversation_id) REFERENCES channel_conversations(id), ADD CONSTRAINT fk_channel_outbox_run FOREIGN KEY (run_id) REFERENCES channel_runs(id), ADD CONSTRAINT fk_channel_outbox_message FOREIGN KEY (message_id) REFERENCES channel_messages(id)');
PREPARE channel_v12_restore_stmt FROM @channel_v12_restore_sql; EXECUTE channel_v12_restore_stmt; DEALLOCATE PREPARE channel_v12_restore_stmt;
SET @channel_v12_restore_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND table_name = 'channel_run_inputs' AND constraint_name = 'fk_channel_run_inputs_run'), 'SELECT 1', 'ALTER TABLE channel_run_inputs ADD CONSTRAINT fk_channel_run_inputs_run FOREIGN KEY (run_id) REFERENCES channel_runs(id), ADD CONSTRAINT fk_channel_run_inputs_inbox FOREIGN KEY (inbox_event_id) REFERENCES channel_inbox_events(id)');
PREPARE channel_v12_restore_stmt FROM @channel_v12_restore_sql; EXECUTE channel_v12_restore_stmt; DEALLOCATE PREPARE channel_v12_restore_stmt;
SET @channel_v12_restore_sql := IF(EXISTS (SELECT 1 FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE() AND table_name = 'channel_callbacks' AND constraint_name = 'fk_channel_callbacks_account'), 'SELECT 1', 'ALTER TABLE channel_callbacks ADD CONSTRAINT fk_channel_callbacks_account FOREIGN KEY (account_id) REFERENCES channel_accounts(id), ADD CONSTRAINT fk_channel_callbacks_conversation FOREIGN KEY (conversation_id) REFERENCES channel_conversations(id), ADD CONSTRAINT fk_channel_callbacks_run FOREIGN KEY (run_id) REFERENCES channel_runs(id), ADD CONSTRAINT fk_channel_callbacks_user FOREIGN KEY (allowed_user_id) REFERENCES tenant_users(id)');
PREPARE channel_v12_restore_stmt FROM @channel_v12_restore_sql; EXECUTE channel_v12_restore_stmt; DEALLOCATE PREPARE channel_v12_restore_stmt;

ALTER TABLE channel_conversations
  MODIFY runtime_fingerprint VARCHAR(64) NOT NULL DEFAULT '',
  MODIFY runtime_fingerprint_version INT NOT NULL DEFAULT 1;
ALTER TABLE channel_runs
  MODIFY runtime_fingerprint VARCHAR(64) NOT NULL DEFAULT '',
  MODIFY runtime_fingerprint_version INT NOT NULL DEFAULT 1;
-- Preserve NULL outbound receipt ids on rollback; converting them back to the
-- v11 empty-string sentinel would be destructive and can collide on the unique key.

SET @channel_v12_run_inputs_column_drop_sql := IF(EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'channel_run_inputs' AND column_name = 'tenant_id'), 'ALTER TABLE channel_run_inputs DROP COLUMN tenant_id', 'SELECT 1');
PREPARE channel_v12_run_inputs_column_drop_stmt FROM @channel_v12_run_inputs_column_drop_sql; EXECUTE channel_v12_run_inputs_column_drop_stmt; DEALLOCATE PREPARE channel_v12_run_inputs_column_drop_stmt;

SET @channel_v12_drop_index_sql := IF(EXISTS (SELECT 1 FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = 'channel_accounts' AND index_name = 'uk_channel_v12_accounts_tenant_id'), 'ALTER TABLE channel_accounts DROP INDEX uk_channel_v12_accounts_tenant_id', 'SELECT 1');
PREPARE channel_v12_drop_index_stmt FROM @channel_v12_drop_index_sql; EXECUTE channel_v12_drop_index_stmt; DEALLOCATE PREPARE channel_v12_drop_index_stmt;
SET @channel_v12_drop_index_sql := IF(EXISTS (SELECT 1 FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = 'channel_identities' AND index_name = 'uk_channel_v12_identities_tenant_id'), 'ALTER TABLE channel_identities DROP INDEX uk_channel_v12_identities_tenant_id', 'SELECT 1');
PREPARE channel_v12_drop_index_stmt FROM @channel_v12_drop_index_sql; EXECUTE channel_v12_drop_index_stmt; DEALLOCATE PREPARE channel_v12_drop_index_stmt;
SET @channel_v12_drop_index_sql := IF(EXISTS (SELECT 1 FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = 'channel_conversations' AND index_name = 'uk_channel_v12_conversations_tenant_id'), 'ALTER TABLE channel_conversations DROP INDEX uk_channel_v12_conversations_tenant_id', 'SELECT 1');
PREPARE channel_v12_drop_index_stmt FROM @channel_v12_drop_index_sql; EXECUTE channel_v12_drop_index_stmt; DEALLOCATE PREPARE channel_v12_drop_index_stmt;
SET @channel_v12_drop_index_sql := IF(EXISTS (SELECT 1 FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = 'channel_inbox_events' AND index_name = 'uk_channel_v12_inbox_events_tenant_id'), 'ALTER TABLE channel_inbox_events DROP INDEX uk_channel_v12_inbox_events_tenant_id', 'SELECT 1');
PREPARE channel_v12_drop_index_stmt FROM @channel_v12_drop_index_sql; EXECUTE channel_v12_drop_index_stmt; DEALLOCATE PREPARE channel_v12_drop_index_stmt;
SET @channel_v12_drop_index_sql := IF(EXISTS (SELECT 1 FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = 'channel_runs' AND index_name = 'uk_channel_v12_runs_tenant_id'), 'ALTER TABLE channel_runs DROP INDEX uk_channel_v12_runs_tenant_id', 'SELECT 1');
PREPARE channel_v12_drop_index_stmt FROM @channel_v12_drop_index_sql; EXECUTE channel_v12_drop_index_stmt; DEALLOCATE PREPARE channel_v12_drop_index_stmt;
SET @channel_v12_drop_index_sql := IF(EXISTS (SELECT 1 FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = 'channel_messages' AND index_name = 'uk_channel_v12_messages_tenant_id'), 'ALTER TABLE channel_messages DROP INDEX uk_channel_v12_messages_tenant_id', 'SELECT 1');
PREPARE channel_v12_drop_index_stmt FROM @channel_v12_drop_index_sql; EXECUTE channel_v12_drop_index_stmt; DEALLOCATE PREPARE channel_v12_drop_index_stmt;
SET @channel_v12_drop_index_sql := IF(EXISTS (SELECT 1 FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = 'tenant_users' AND index_name = 'uk_channel_v12_tenant_users_tenant_id'), 'ALTER TABLE tenant_users DROP INDEX uk_channel_v12_tenant_users_tenant_id', 'SELECT 1');
PREPARE channel_v12_drop_index_stmt FROM @channel_v12_drop_index_sql; EXECUTE channel_v12_drop_index_stmt; DEALLOCATE PREPARE channel_v12_drop_index_stmt;
SET @channel_v12_drop_index_sql := IF(EXISTS (SELECT 1 FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = 'tenant_sessions' AND index_name = 'uk_channel_v12_tenant_sessions_tenant_id'), 'ALTER TABLE tenant_sessions DROP INDEX uk_channel_v12_tenant_sessions_tenant_id', 'SELECT 1');
PREPARE channel_v12_drop_index_stmt FROM @channel_v12_drop_index_sql; EXECUTE channel_v12_drop_index_stmt; DEALLOCATE PREPARE channel_v12_drop_index_stmt;
SET @channel_v12_drop_index_sql := IF(EXISTS (SELECT 1 FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = 'tenant_session_messages' AND index_name = 'uk_channel_v12_tenant_session_messages_tenant_id'), 'ALTER TABLE tenant_session_messages DROP INDEX uk_channel_v12_tenant_session_messages_tenant_id', 'SELECT 1');
PREPARE channel_v12_drop_index_stmt FROM @channel_v12_drop_index_sql; EXECUTE channel_v12_drop_index_stmt; DEALLOCATE PREPARE channel_v12_drop_index_stmt;
