SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS tenant_goals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  goal_key VARCHAR(64) NOT NULL,
  objective LONGTEXT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  session_id VARCHAR(128) NULL,
  cwd VARCHAR(1024) NULL,
  model VARCHAR(128) NULL,
  turn_budget INT NOT NULL,
  token_budget INT NOT NULL,
  turns_used INT NOT NULL DEFAULT 0,
  input_tokens INT NOT NULL DEFAULT 0,
  output_tokens INT NOT NULL DEFAULT 0,
  last_blocker TEXT NULL,
  repeated_blocker_count INT NOT NULL DEFAULT 0,
  last_checkpoint VARCHAR(255) NULL,
  last_reason TEXT NULL,
  last_next_action TEXT NULL,
  error_message TEXT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_tenant_goals_key (tenant_id, user_id, goal_key),
  KEY idx_tenant_goals_status (tenant_id, user_id, status, updated_at),
  KEY idx_tenant_goals_session (tenant_id, user_id, session_id),
  KEY idx_tenant_goals_recent (tenant_id, user_id, updated_at),
  CONSTRAINT fk_tenant_goals_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_tenant_goals_user FOREIGN KEY (user_id) REFERENCES tenant_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tenant_goal_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  goal_id BIGINT UNSIGNED NOT NULL,
  event_key VARCHAR(64) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  message TEXT NULL,
  session_id VARCHAR(128) NULL,
  turn_index INT NOT NULL DEFAULT 0,
  input_tokens INT NOT NULL DEFAULT 0,
  output_tokens INT NOT NULL DEFAULT 0,
  duration_ms BIGINT NOT NULL DEFAULT 0,
  checkpoint VARCHAR(255) NULL,
  status VARCHAR(32) NULL,
  reason TEXT NULL,
  next_action TEXT NULL,
  blocker_key VARCHAR(255) NULL,
  error_message TEXT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_tenant_goal_events_key (goal_id, event_key),
  KEY idx_tenant_goal_events_goal (goal_id, created_at),
  KEY idx_tenant_goal_events_user_recent (tenant_id, user_id, created_at),
  CONSTRAINT fk_tenant_goal_events_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_tenant_goal_events_user FOREIGN KEY (user_id) REFERENCES tenant_users(id),
  CONSTRAINT fk_tenant_goal_events_goal FOREIGN KEY (goal_id) REFERENCES tenant_goals(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
