SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS agent_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  owner_user_id BIGINT UNSIGNED NULL,
  owner_key VARCHAR(128) NOT NULL,
  profile_key VARCHAR(64) NOT NULL,
  scope VARCHAR(24) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  description TEXT NULL,
  profile_version INT UNSIGNED NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  config_json JSON NOT NULL,
  requested_hash CHAR(64) NOT NULL,
  effective_hash CHAR(64) NOT NULL,
  validation_json JSON NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  updated_by_user_id BIGINT UNSIGNED NOT NULL,
  published_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_agent_profiles_tenant_id (tenant_id, id),
  UNIQUE KEY uk_agent_profiles_version_owner (tenant_id, profile_key, profile_version, owner_key),
  KEY idx_agent_profiles_catalog (tenant_id, scope, status, updated_at),
  KEY idx_agent_profiles_owner (tenant_id, owner_user_id, profile_key, status),
  CONSTRAINT chk_agent_profiles_scope CHECK (scope IN ('builtin', 'tenant_shared', 'user_private')),
  CONSTRAINT chk_agent_profiles_status CHECK (status IN ('draft', 'validating', 'published', 'archived')),
  CONSTRAINT fk_agent_profiles_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_agent_profiles_owner_tenant FOREIGN KEY (tenant_id, owner_user_id) REFERENCES tenant_users(tenant_id, id),
  CONSTRAINT fk_agent_profiles_created_by_tenant FOREIGN KEY (tenant_id, created_by_user_id) REFERENCES tenant_users(tenant_id, id),
  CONSTRAINT fk_agent_profiles_updated_by_tenant FOREIGN KEY (tenant_id, updated_by_user_id) REFERENCES tenant_users(tenant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_profile_assignments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  surface VARCHAR(32) NOT NULL,
  profile_id BIGINT UNSIGNED NOT NULL,
  assigned_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_agent_profile_assignments_tenant_id (tenant_id, id),
  UNIQUE KEY uk_agent_profile_assignments_surface (tenant_id, user_id, surface),
  KEY idx_agent_profile_assignments_profile (tenant_id, profile_id),
  CONSTRAINT fk_agent_profile_assignments_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_agent_profile_assignments_user_tenant FOREIGN KEY (tenant_id, user_id) REFERENCES tenant_users(tenant_id, id),
  CONSTRAINT fk_agent_profile_assignments_profile_tenant FOREIGN KEY (tenant_id, profile_id) REFERENCES agent_profiles(tenant_id, id),
  CONSTRAINT fk_agent_profile_assignments_actor_tenant FOREIGN KEY (tenant_id, assigned_by_user_id) REFERENCES tenant_users(tenant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_profile_channel_bindings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  profile_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  provider VARCHAR(32) NOT NULL,
  binding_key VARCHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  archived_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_agent_profile_channel_bindings_tenant_id (tenant_id, id),
  UNIQUE KEY uk_agent_profile_channel_bindings_profile (tenant_id, profile_id),
  KEY idx_agent_profile_channel_bindings_account (tenant_id, account_id, provider, status),
  CONSTRAINT chk_agent_profile_channel_bindings_status CHECK (status IN ('active', 'archived')),
  CONSTRAINT fk_agent_profile_channel_bindings_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_agent_profile_channel_bindings_profile_tenant FOREIGN KEY (tenant_id, profile_id) REFERENCES agent_profiles(tenant_id, id),
  CONSTRAINT fk_agent_profile_channel_bindings_account_tenant FOREIGN KEY (tenant_id, account_id) REFERENCES channel_accounts(tenant_id, id),
  CONSTRAINT fk_agent_profile_channel_bindings_actor_tenant FOREIGN KEY (tenant_id, created_by_user_id) REFERENCES tenant_users(tenant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
