SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS channel_interactions (
  id CHAR(36) NOT NULL,
  tenant_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  conversation_id BIGINT UNSIGNED NOT NULL,
  run_id CHAR(36) NOT NULL,
  session_id BIGINT UNSIGNED NULL,
  kind VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  external_chat_id VARCHAR(255) NOT NULL,
  external_thread_id VARCHAR(255) NOT NULL DEFAULT '',
  external_user_id VARCHAR(255) NOT NULL,
  scope_hash BINARY(32) NOT NULL,
  allowed_user_id BIGINT UNSIGNED NOT NULL,
  question_ciphertext MEDIUMBLOB NOT NULL,
  resume_checkpoint_ciphertext MEDIUMBLOB NOT NULL,
  answer_ciphertext MEDIUMBLOB NULL,
  nonce_hash BINARY(32) NOT NULL,
  runtime_fingerprint VARCHAR(64) NOT NULL,
  runtime_fingerprint_version INT NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  answered_at DATETIME(3) NULL,
  consumed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_channel_interactions_account_nonce (account_id, nonce_hash),
  KEY idx_channel_interactions_conversation_status (tenant_id, account_id, conversation_id, status),
  KEY idx_channel_interactions_chat_status (tenant_id, account_id, external_chat_id, status),
  KEY idx_channel_interactions_expiry (status, expires_at),
  CONSTRAINT chk_channel_interactions_status CHECK (status IN ('pending', 'answered', 'expired', 'cancelled')),
  CONSTRAINT fk_channel_interactions_account_tenant FOREIGN KEY (tenant_id, account_id) REFERENCES channel_accounts(tenant_id, id),
  CONSTRAINT fk_channel_interactions_conversation_tenant FOREIGN KEY (tenant_id, conversation_id) REFERENCES channel_conversations(tenant_id, id),
  CONSTRAINT fk_channel_interactions_run_tenant FOREIGN KEY (tenant_id, run_id) REFERENCES channel_runs(tenant_id, id),
  CONSTRAINT fk_channel_interactions_user_tenant FOREIGN KEY (tenant_id, allowed_user_id) REFERENCES tenant_users(tenant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
