SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS tenant_telemetry_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  event_name VARCHAR(128) NOT NULL,
  category VARCHAR(64) NULL,
  source VARCHAR(128) NULL,
  status VARCHAR(32) NULL,
  trace_id VARCHAR(128) NULL,
  session_id BIGINT UNSIGNED NULL,
  resource_type VARCHAR(64) NULL,
  resource_id VARCHAR(128) NULL,
  model VARCHAR(128) NULL,
  tool_name VARCHAR(128) NULL,
  duration_ms BIGINT NULL,
  input_tokens INT UNSIGNED NOT NULL DEFAULT 0,
  output_tokens INT UNSIGNED NOT NULL DEFAULT 0,
  cache_creation_input_tokens INT UNSIGNED NOT NULL DEFAULT 0,
  cache_read_input_tokens INT UNSIGNED NOT NULL DEFAULT 0,
  cache_creation_ephemeral_1h_input_tokens INT UNSIGNED NOT NULL DEFAULT 0,
  cache_creation_ephemeral_5m_input_tokens INT UNSIGNED NOT NULL DEFAULT 0,
  error_message VARCHAR(1024) NULL,
  properties_json JSON NULL,
  occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_telemetry_tenant_recent (tenant_id, occurred_at, id),
  KEY idx_telemetry_user_recent (tenant_id, user_id, occurred_at),
  KEY idx_telemetry_trace (tenant_id, trace_id, occurred_at),
  KEY idx_telemetry_event (tenant_id, event_name, occurred_at),
  KEY idx_telemetry_category_status (tenant_id, category, status, occurred_at),
  KEY idx_telemetry_session (tenant_id, session_id, occurred_at),
  CONSTRAINT fk_telemetry_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_telemetry_user FOREIGN KEY (user_id) REFERENCES tenant_users(id),
  CONSTRAINT fk_telemetry_session FOREIGN KEY (session_id) REFERENCES tenant_sessions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
