import { useEffect, useState } from "react";
import { deletePromptTemplate, listPromptTemplates, savePromptTemplate } from "../../lib/api";
import type { IdentityConfig, PromptTemplate } from "../../lib/types";
export function PromptManager({ identity }: { identity: IdentityConfig }) {
  const [items, setItems] = useState<PromptTemplate[]>([]), [edit, setEdit] = useState<PromptTemplate>({ id: 0, title: "", content: "", category: "", pinned: false, sort_order: 0 }), [error, setError] = useState("");
  async function load() { try { setItems(await listPromptTemplates(identity)); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  useEffect(() => { void load(); }, [identity.apiBase, identity.tenantKey, identity.userId]);
  async function save() { try { await savePromptTemplate(identity, edit); setEdit({ id: 0, title: "", content: "", category: "", pinned: false, sort_order: 0 }); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  return <section className="p2-management-panel" aria-label="Common prompts"><header className="p2-management-toolbar"><div><h2>常用提示词</h2><p>保存后可在 Composer 中选择并继续编辑。</p></div></header><div className="p2-management-create"><label>标题<input value={edit.title} onChange={(e) => setEdit({ ...edit, title: e.target.value })} /></label><label>分类<input value={edit.category} onChange={(e) => setEdit({ ...edit, category: e.target.value })} /></label><label className="full">提示词内容<textarea rows={7} value={edit.content} onChange={(e) => setEdit({ ...edit, content: e.target.value })} /></label><label><input type="checkbox" checked={edit.pinned} onChange={(e) => setEdit({ ...edit, pinned: e.target.checked })} />置顶</label><button className="primary" type="button" disabled={!edit.title.trim() || !edit.content.trim()} onClick={() => void save()}>{edit.id ? "保存修改" : "新增提示词"}</button></div>{error ? <p role="alert">{error}</p> : null}<div className="p2-management-list">{items.map((item) => <article key={item.id}><strong>{item.title}</strong><p>{item.category} {item.pinned ? " · 置顶" : ""}</p><p>{item.content}</p><button type="button" onClick={() => setEdit(item)}>编辑</button><button type="button" onClick={() => { if (window.confirm("确认删除？")) void deletePromptTemplate(identity, item.id).then(load); }}>删除</button></article>)}</div></section>;
}
