// Web Agent 界面文案字典（原样迁自 WebAgentPage）。
export const agentCopy = {
  en: {
    newSession: "New Session",
    search: "Search",
    refresh: "Refresh",
    permissions: "Permissions",
    backToWebui: "Main WebUI",
    workspace: "Workspace",
    changeWorkspace: "Change",
    workspaceLower: "workspace",
    noWorkspace: "No workspace",
    validateCwdHint: "Validate a cwd to start",
    validate: "Validate",
    workspaceChecking: "Checking workspace...",
    workspaceEnterAbsolutePath: "Enter an absolute local path. It will be checked automatically.",
    workspaceReadyState: "Ready",
    filterWorkspaces: "Filter recent workspaces",
    filterSessions: "Search sessions or workspaces",
    noRealWorkspaces: "No real workspaces loaded.",
    workspaceNotSelected: "Workspace not selected",
    sessions: "Sessions",
    sessionsLower: "sessions",
    expandWorkspaceSessions: "Expand workspace sessions",
    collapseWorkspaceSessions: "Collapse workspace sessions",
    webAgentSession: "Web Agent Session",
    elapsed: "Elapsed",
    filesRead: "Files read",
    commands: "Commands",
    editing: "Editing",
    delta: "Delta",
    filesUnit: "files",
    linesUnit: "lines",
    noSessionsTitle: "No Web Agent sessions in this tenant.",
    noSessionsBody: "Choose a workspace and create a session. This real view does not seed fake sessions.",
    blankSessionTitle: "What should the agent do?",
    blankSessionBody: "Send a prompt to start. Runtime details appear only while the agent is working.",
    blankSuggestions: [
      "Explain this project's architecture",
      "Find and fix a bug",
      "Add tests for recent changes",
      "Review the latest commits"
    ],
    user: "User",
    assistant: "Assistant",
    system: "System",
    task: "Task",
    cwdUnknown: "cwd unknown",
    noEvents: "No event stream yet for this session.",
    noMessages: "No conversation messages yet. Lifecycle events are in Progress.",
    messageEvent: "message",
    loadingSessions: "Loading real agent sessions...",
    messagePlaceholder: "Message the current agent session...",
    selectSessionPlaceholder: "Create or select a session first...",
    jumpToLatest: "Jump to latest",
    gitRepo: "git repo",
    context: "Context",
    cacheHitTitle: "Prompt cache hit rate",
    promptMode: "Mode",
    newSessionPromptMode: "New session prompt mode",
    promptModes: { chat: "Chat", code: "Code" },
    cancel: "Cancel",
    send: "Send",
    pendingInputs: "Queued inputs",
    movePendingInputUp: "Move up",
    adjustDirection: "Adjust direction",
    editPendingInput: "Edit message",
    deletePendingInput: "Delete queued input",
    pendingInputMore: "More queued input actions",
    openPendingInputSideChat: "Open in side chat",
    retryPendingInput: "Retry queued input",
    closeQueue: "Turn off queue",
    openQueue: "Turn on queue",
    queueDisabled: "Queue is off",
    workspaceDetail: "Workspace Detail",
    tabs: { progress: "Progress", runs: "Runs", files: "Files", permissions: "Permissions", trace: "Trace", usage: "Usage" },
    startInWorkspace: "Start in current workspace",
    workspaceCwd: "Workspace cwd",
    title: "Title",
    optionalTitle: "Optional session title",
    firstPrompt: "First prompt",
    firstPromptPlaceholder: "What should the agent do in this workspace?",
    createSession: "Create Session",
    storageMissingTitle: "Tenant storage is not enabled",
    storageMissingBody: "The page is live, but session/task history needs MySQL tenant storage. Workspace validation still works.",
    apiErrorTitle: "API error",
    restoreLocalTestIdentity: "Restore Web Agent test identity",
    selectSessionInspect: "Select a session to inspect progress.",
    status: "Status",
    model: "Model",
    trace: "Trace",
    traceMissing: "trace missing",
    started: "Started",
    runs: "Runs",
    run: "Run",
    conversationId: "Conversation",
    eventCount: "Events",
    totalTokens: "Total tokens",
    inputTokens: "Input tokens",
    outputTokens: "Output tokens",
    toolCalls: "Tool calls",
    duration: "Duration",
    completedRuns: "Completed",
    failedRuns: "Failed",
    cancelledRuns: "Cancelled",
    timeoutRuns: "Timed out",
    runningRuns: "Running",
    contextLength: "Context length",
    cacheCreateTokens: "Cache create",
    cacheReadTokens: "Cache read",
    cacheEphemeralTokens: "Cache 5m/1h",
    serviceTier: "Service tier",
    inferenceGeo: "Inference geo",
    speed: "Speed",
    initialMessages: "Initial messages",
    stopReason: "Stop reason",
    currentFile: "Current file",
    readFiles: "Read files",
    changedFiles: "Changed files",
    lineDelta: "Line delta",
    noFileEvents: "No file events recorded yet.",
    editedFilesGroup: "Edited",
    readFilesGroup: "Read",
    // Shown instead of a line count when the file body was too large to capture
    // inline, so the server has no measurement to report.
    lineDeltaUnavailable: "size not captured",
    fileChangeKinds: {
      created: "created",
      modified: "modified",
      deleted: "deleted"
    } as Record<string, string>,
    fileObjects: {
      dir: "directory",
      symlink: "symlink"
    } as Record<string, string>,
    mode: "Mode",
    pending: "Pending",
    sandbox: "Sandbox",
    localWorkspace: "local workspace",
    permissionNote: "Permission mode is always visible in the composer. Pending approvals from the event stream will surface here.",
    noPermissionRequests: "No permission requests recorded yet.",
    permissionRequest: "Permission request",
    approve: "Approve",
    deny: "Deny",
    permissionDecisionSaved: "Permission decision saved",
    permission: "permission",
    effort: "effort",
    processed: "Processed",
    readFilesCount: "Read {count} files",
    commandsRunCount: "Ran {count} commands",
    currentlyTouching: "Current file",
    changedSummary: "{count} files changed",
    workspaceReady: "Workspace ready",
    chooseWorkspaceFirst: "Choose a workspace cwd first.",
    defaultPrompt: "Start a Web Agent session for this workspace.",
    createdSession: "Created Web Agent session",
    sentMessage: "Sent message to session",
    cancelledSession: "Cancelled session",
    language: "Language",
    hideNavigation: "Hide navigation",
    showNavigation: "Show navigation",
    toggleLeftRail: "Toggle left rail",
    toggleRightPanel: "Toggle right panel",
    toggleTheme: "Toggle theme",
    resizeLeftRail: "Resize left rail",
    resizeRightPanel: "Resize right panel",
    closePanels: "Close panels",
    copyMessage: "Copy",
    copyCode: "Copy code",
    copied: "Copied",
    imageAttachment: "Add image",
    imageAttachments: "Image attachments",
    removeImage: "Remove image",
    imageAttachmentInvalid: "Only image files can be attached",
    imageAttachmentLimit: "You can attach up to {n} images",
    imageGeneration: "Image generation",
    imageGenerate: "Generate",
    imageEdit: "Edit / redraw",
    imagePrompt: "Prompt",
    imagePromptPlaceholder: "Describe the image you want to create...",
    imageSource: "Source image",
    imageQuality: "Quality",
    imageSize: "Size",
    imageFormat: "Format",
    imageBackground: "Background",
    imageSourceSelect: "Select a source image",
    imageUpload: "Upload image",
    imageGenerateAction: "Generate image",
    imageEditAction: "Edit image",
    imageGenerating: "Generating...",
    imageLoadingHistory: "Loading image history...",
    imageNoHistory: "No generated images yet.",
    imageRetry: "Retry image generation",
    imageDownload: "Download image",
    imageError: "Image generation failed",
    retryMessage: "Retry",
    cmdkTitle: "Command palette",
    cmdkPlaceholder: "Search commands, sessions, workspaces…",
    cmdkEmpty: "No matches",
    cmdkActions: "Actions",
    cmdkWorkspaces: "Workspaces",
    cmdkSessions: "Sessions",
    hideDetails: "Hide details",
    showDetails: "Show details",
    eventStream: "Events",
    live: "live",
    streamError: "Agent event stream failed",
    streamStale: "Agent is still running but no new event arrived for 90s. Refreshed task state; the server runner will fail the task automatically if the provider stays idle.",
    streamStates: { idle: "idle", connecting: "connecting", live: "live", closed: "closed", error: "error" },
    composerRuntime: "Composer runtime",
    runtimeTopbar: "Runtime summary",
    provider: "Provider",
    tools: "Tools",
    mcp: "MCP",
    goal: "Goal",
    composerStates: { idle: "no session", ready: "ready", sending: "sending", running: "running", cancelling: "cancelling" },
    agentWorking: "Agent is working",
    thinkingStates: {
      sending: "Sending",
      sendingDetail: "Preparing the turn",
      connecting: "Connecting",
      thinking: "Thinking",
      readingContext: "Reading context",
      runningCommand: "Running tools",
      liveDetail: "live"
    },
    sending: "Sending",
    cancelling: "Cancelling",
    slashCommands: "Slash commands",
    slashHint: "Slash commands  up/down select  tab complete  enter run",
    slashLoading: "Loading slash commands...",
    slashEmpty: "No matching slash commands.",
    slashError: "Slash commands unavailable",
    slashNoDescription: "No description",
    nextStepsHint: "Suggested next steps",
    recentAgentEvidence: "Recent agent evidence",
    toolActivity: "Tool activity",
    toolStatus: { running: "running", done: "done", error: "error" },
    activityTimeline: "Activity timeline",
    timelinePrompt: "Prompt sent",
    timelineStarted: "Run started",
    timelineReply: "Streaming reply",
    timelinePermission: "Permission requested",
    timelineCompleted: "Completed",
    timelineFailed: "Failed",
    timelineCancelled: "Cancelled",
    timelineExpand: "Click to view payload",
    showEarlierMessages: "Show {n} earlier messages",
    replyDuration: "Reply time",
    tokensUsed: "Tokens used",
    ranCommands: "Ran {n} commands",
    runningCommand: "Running",
    commandDetails: "View command details",
    thinkingMode: "Thinking",
    thinkingSummary: "Reasoning",
    thinkingCompleted: "Completed",
    thinkingFailed: "Failed",
    thinkingCancelled: "Cancelled",
    thinkingTimedOut: "Timed out",
    expandThinking: "Expand thinking",
    collapseThinking: "Collapse thinking",
    thinkingTurn: "turn {n}",
    thinkingPhase: "phase {n}",
    thinkingLines: "{n} lines",
    thinkingTokensUnavailable: "tokens unavailable",
    thinkingModes: { full: "Full", summary: "Summary", hidden: "Hidden" },
    subAgents: "Sub-agents",
    subAgentStatus: { running: "running", done: "done", error: "error", cancelled: "cancelled" }
  },
  zh: {
    newSession: "新会话",
    search: "搜索",
    refresh: "刷新",
    permissions: "权限",
    backToWebui: "主 WebUI",
    workspace: "工作区",
    changeWorkspace: "切换",
    workspaceLower: "工作区",
    noWorkspace: "未选择工作区",
    validateCwdHint: "先验证 cwd 后开始",
    validate: "验证",
    workspaceChecking: "正在检查工作区...",
    workspaceEnterAbsolutePath: "输入本机绝对路径后会自动检查。",
    workspaceReadyState: "可用",
    filterWorkspaces: "筛选最近工作区",
    filterSessions: "搜索会话或工作区",
    noRealWorkspaces: "还没有真实工作区记录。",
    workspaceNotSelected: "未选择工作区",
    sessions: "会话",
    sessionsLower: "个会话",
    expandWorkspaceSessions: "展开工作区会话",
    collapseWorkspaceSessions: "折叠工作区会话",
    webAgentSession: "Web Agent 会话",
    elapsed: "耗时",
    filesRead: "读取文件",
    commands: "命令",
    editing: "正在编辑",
    delta: "改动",
    filesUnit: "个文件",
    linesUnit: "行",
    noSessionsTitle: "当前租户还没有 Web Agent 会话。",
    noSessionsBody: "选择工作区后创建新会话。真实页面不会注入假的 seed 会话。",
    blankSessionTitle: "我们该构建什么？",
    blankSessionBody: "发送指令后开始执行；耗时、文件、命令等信息只在运行时出现。",
    blankSuggestions: [
      "讲解这个项目的整体架构",
      "找出并修复一个 bug",
      "为最近的改动补测试",
      "审查最近的提交"
    ],
    user: "用户",
    assistant: "AI 回复",
    system: "系统",
    task: "任务",
    cwdUnknown: "cwd 未知",
    noEvents: "这个会话还没有事件流。",
    noMessages: "还没有对话消息，生命周期事件在进度里查看。",
    messageEvent: "消息",
    loadingSessions: "正在加载真实 agent 会话...",
    messagePlaceholder: "给当前 agent 会话发送消息...",
    selectSessionPlaceholder: "先创建或选择一个会话...",
    jumpToLatest: "回到最新",
    gitRepo: "Git 仓库",
    context: "上下文",
    cacheHitTitle: "Prompt 缓存命中率",
    promptMode: "模式",
    newSessionPromptMode: "新会话模式",
    promptModes: { chat: "Chat", code: "Code" },
    cancel: "取消",
    send: "发送",
    pendingInputs: "等待输入",
    movePendingInputUp: "上移候选",
    adjustDirection: "调整方向",
    editPendingInput: "编辑消息",
    deletePendingInput: "删除等待输入",
    pendingInputMore: "更多等待输入操作",
    openPendingInputSideChat: "在侧边聊天中打开",
    retryPendingInput: "重试等待输入",
    closeQueue: "关闭排队",
    openQueue: "开启排队",
    queueDisabled: "排队已关闭",
    workspaceDetail: "工作区详情",
    tabs: { progress: "进度", runs: "运行", files: "文件", permissions: "权限", trace: "Trace", usage: "用量" },
    startInWorkspace: "在当前工作区开始",
    workspaceCwd: "工作区 cwd",
    title: "标题",
    optionalTitle: "可选会话标题",
    firstPrompt: "首条指令",
    firstPromptPlaceholder: "希望 agent 在这个工作区做什么？",
    createSession: "创建会话",
    storageMissingTitle: "未启用租户存储",
    storageMissingBody: "页面已经启动，但会话/任务历史依赖 MySQL tenant storage。工作区验证仍然可用。",
    apiErrorTitle: "API 错误",
    restoreLocalTestIdentity: "恢复 Web Agent 测试身份",
    selectSessionInspect: "选择一个会话后查看进度。",
    status: "状态",
    model: "模型",
    trace: "Trace",
    traceMissing: "缺少 trace",
    started: "开始时间",
    runs: "运行次数",
    run: "运行",
    conversationId: "会话 ID",
    eventCount: "事件数",
    totalTokens: "总 token",
    inputTokens: "输入 token",
    outputTokens: "输出 token",
    toolCalls: "工具调用",
    duration: "总耗时",
    completedRuns: "已完成",
    failedRuns: "失败",
    cancelledRuns: "已取消",
    timeoutRuns: "超时",
    runningRuns: "运行中",
    contextLength: "上下文长度",
    cacheCreateTokens: "缓存写入",
    cacheReadTokens: "缓存读取",
    cacheEphemeralTokens: "缓存 5m/1h",
    serviceTier: "服务层",
    inferenceGeo: "推理区域",
    speed: "速度",
    initialMessages: "历史消息",
    stopReason: "停止原因",
    currentFile: "当前文件",
    readFiles: "读取文件",
    changedFiles: "改动文件",
    lineDelta: "行数变化",
    noFileEvents: "还没有文件事件。",
    editedFilesGroup: "已修改",
    readFilesGroup: "已读取",
    lineDeltaUnavailable: "体积过大未采集",
    fileChangeKinds: {
      created: "新建",
      modified: "修改",
      deleted: "删除"
    } as Record<string, string>,
    fileObjects: {
      dir: "目录",
      symlink: "符号链接"
    } as Record<string, string>,
    mode: "模式",
    pending: "待处理",
    sandbox: "沙箱",
    localWorkspace: "本地工作区",
    permissionNote: "权限模式常驻在底部 composer。事件流里的待审批请求会显示在这里。",
    noPermissionRequests: "还没有权限请求。",
    permissionRequest: "权限请求",
    approve: "允许",
    deny: "拒绝",
    permissionDecisionSaved: "权限决策已保存",
    permission: "权限",
    effort: "强度",
    processed: "已处理",
    readFilesCount: "已读取 {count} 个文件",
    commandsRunCount: "已运行 {count} 条命令",
    currentlyTouching: "当前文件",
    changedSummary: "{count} 个文件已更改",
    workspaceReady: "工作区已就绪",
    chooseWorkspaceFirst: "请先选择工作区 cwd。",
    defaultPrompt: "为这个工作区启动 Web Agent 会话。",
    createdSession: "已创建 Web Agent 会话",
    sentMessage: "已发送消息到会话",
    cancelledSession: "已取消会话",
    language: "语言",
    hideNavigation: "隐藏导航",
    showNavigation: "显示导航",
    toggleLeftRail: "切换左侧栏",
    toggleRightPanel: "切换右侧面板",
    toggleTheme: "切换深浅主题",
    resizeLeftRail: "拖拽调整左栏宽度",
    resizeRightPanel: "拖拽调整右栏宽度",
    closePanels: "关闭面板",
    copyMessage: "复制",
    copyCode: "复制代码",
    copied: "已复制",
    imageAttachment: "添加图片",
    imageAttachments: "图片附件",
    removeImage: "移除图片",
    imageAttachmentInvalid: "只能添加图片文件",
    imageAttachmentLimit: "最多可添加 {n} 张图片",
    imageGeneration: "图片生成",
    imageGenerate: "生成",
    imageEdit: "编辑 / 重绘",
    imagePrompt: "提示词",
    imagePromptPlaceholder: "描述你想创建的图片...",
    imageSource: "源图片",
    imageQuality: "质量",
    imageSize: "尺寸",
    imageFormat: "格式",
    imageBackground: "背景",
    imageSourceSelect: "选择源图片",
    imageUpload: "上传图片",
    imageGenerateAction: "生成图片",
    imageEditAction: "编辑图片",
    imageGenerating: "生成中...",
    imageLoadingHistory: "正在加载图片历史...",
    imageNoHistory: "还没有生成图片。",
    imageRetry: "重试图片生成",
    imageDownload: "下载图片",
    imageError: "图片生成失败",
    retryMessage: "重试",
    cmdkTitle: "命令面板",
    cmdkPlaceholder: "搜索命令、会话、工作区…",
    cmdkEmpty: "无匹配项",
    cmdkActions: "操作",
    cmdkWorkspaces: "工作区",
    cmdkSessions: "会话",
    hideDetails: "隐藏详情",
    showDetails: "显示详情",
    eventStream: "事件流",
    live: "实时",
    streamError: "Agent 事件流连接失败",
    streamStale: "Agent 仍在运行，但 90 秒内没有新事件。页面已刷新任务状态；如果 provider 持续无输出，服务端会自动将任务置为失败。",
    streamStates: { idle: "空闲", connecting: "连接中", live: "实时", closed: "已关闭", error: "错误" },
    composerRuntime: "Composer 运行状态",
    runtimeTopbar: "运行时摘要",
    provider: "Provider",
    tools: "工具",
    mcp: "MCP",
    goal: "目标",
    composerStates: { idle: "未选择会话", ready: "可发送", sending: "发送中", running: "运行中", cancelling: "取消中" },
    agentWorking: "Agent 正在工作",
    thinkingStates: {
      sending: "正在发送",
      sendingDetail: "正在准备本轮任务",
      connecting: "正在连接",
      thinking: "正在思考",
      readingContext: "正在读取上下文",
      runningCommand: "正在执行工具",
      liveDetail: "运行中"
    },
    sending: "发送中",
    cancelling: "取消中",
    slashCommands: "Slash 命令",
    slashHint: "Slash 命令  上下选择  Tab 补全  Enter 执行",
    slashLoading: "正在加载 Slash 命令...",
    slashEmpty: "没有匹配的 Slash 命令。",
    slashError: "Slash 命令不可用",
    slashNoDescription: "暂无描述",
    nextStepsHint: "建议的下一步",
    recentAgentEvidence: "最近 Agent 证据",
    toolActivity: "工具活动",
    toolStatus: { running: "运行中", done: "完成", error: "错误" },
    activityTimeline: "执行时间线",
    timelinePrompt: "发送指令",
    timelineStarted: "开始执行",
    timelineReply: "生成回复",
    timelinePermission: "请求权限",
    timelineCompleted: "已完成",
    timelineFailed: "失败",
    timelineCancelled: "已取消",
    timelineExpand: "点击查看 payload",
    showEarlierMessages: "显示更早的 {n} 条消息",
    replyDuration: "回复耗时",
    tokensUsed: "本轮 token 用量",
    ranCommands: "已运行 {n} 条命令",
    runningCommand: "正在运行",
    commandDetails: "查看命令详情",
    thinkingMode: "思考过程",
    thinkingSummary: "思考过程",
    thinkingCompleted: "已完成",
    thinkingFailed: "已失败",
    thinkingCancelled: "已取消",
    thinkingTimedOut: "已超时",
    expandThinking: "展开思考",
    collapseThinking: "收起思考",
    thinkingTurn: "第 {n} 回合",
    thinkingPhase: "阶段 {n}",
    thinkingLines: "{n} 行",
    thinkingTokensUnavailable: "token 未单独统计",
    thinkingModes: { full: "完整", summary: "摘要折叠", hidden: "隐藏" },
    subAgents: "子代理",
    subAgentStatus: { running: "运行中", done: "完成", error: "错误", cancelled: "已取消" }
  }
} as const;

export type AgentCopy = (typeof agentCopy)[keyof typeof agentCopy];
